apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: imrishav/gitops01:812760f8a3ad592e6a44dfe07f544feb27463b98
          imagePullPolicy: Always
          ports:
            - containerPort: 80
