apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: imrishav/gitops-01:dc647251ef068d848c1f96916280212edf651a2a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
